// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatepaymenttableagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepaymenttableagain));
        
        string IMigrationMetadata.Id
        {
            get { return "202010061313091_update-payment-table-again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
